me:
  email: email
hegdeflutes:
  email: email
server:
  port: 3000
  cors: none
  env: dev
  apiKey: test
dbconfig:
  uri: test
  dbname: test
tradecredconfig:
  base: test
  refreshtoken: test
  dealscheckschedule: 10
callmebot:
  whatsapp:
    apikey: test
    base: https://api.callmebot.com/whatsapp.php
    phone: 12839021
